config/routes.rb
Rails.application.routes.draw do
  post '/random_resturant' => 'restaurants#random_restaurant'
  get '/login' => 'session#new' 
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  root to: 'restaurants#home'
  resources :users
  resources :restaurants
  resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
 end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    unless @current_user.present?
      session[:user_id] = nil
    end
  end

  def check_if_logged_in
    redirect_to login_path unless @current_user.present?
  end

  def check_if_admin
    redirect_to login_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false

  def random_restaurant
     restaurant = Restaurant.all.sample
     redirect_to restaurant_path(restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create restaurant_params

    redirect_to '/restaurants'
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find params[:id]
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    restaurant = Restaurant.find params[:id]
    restaurant.update restaurant_params

    redirect_to restaurant_path(restaurant.id)
  end

  def destroy
    Restaurant.destroy params[:id]

    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit( :name, :price, :cuisine, :location, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :check_if_logged_in, except: [:index, :show ]

  def new
    @review = Review.new
    @restaurant = Restaurant.find params[:id]
  end

  def create
  @current_user.reviews.create review_params
  redirect_to reviews_path

  end

  def index
    @reviews = Review.all
  end

  def show
  end

  def edit
    @review = Review.find params[:id]
    check_ownership
  end

  def update
    @review = Review.find params[:id]

    redirect_to login_path and return unelss @review.user == @current_user
    redirect_to review_path(@review.id)
  end

  def destroy
    Review.destroy params[:id]

    redirect_to reviews_path
  end

  private
  def check_ownership
    redirect_to login_path and return unless @review.user == @current.user
  end
  def review_params
    params.require(:review).permit( :user, :rating, :comment, :restaurant)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]

    # successful login?
    if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
      redirect_to '/' # go to show page (/users/10 etc)
    else
      flash[:error] = 'Invalid email or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, except: [ :new, :create ]
  before_action :check_if_admin, only: [ :index ]

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Ultimate Decision</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Material Design Lite</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">
    <link rel="shortcut icon" href="images/favicon.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">

    <link rel="stylesheet" href="../stylesheets/main.css">
    <style>
      #view-source {
        position: fixed;
        display: block;
        right: 0;
        bottom: 0;
        margin-right: 40px;
        margin-bottom: 40px;
        z-index: 900;
      }
    </style>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
        <div class="mdl-layout--large-screen-only mdl-layout__header-row"></div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
          <h3>The Ultimate Decision</h3>
          <div class="login" id="main-login">
            <% if @current_user.present? %>
            Logged in as <%= @current_user.name %>
            <% if @current_user.admin? %>
            (admin)
            <% end %>
            <%= link_to "Logout", login_path, method: 'delete', :class => "mdl-button" %>
            <% else %>
            <%= link_to "Login", login_path, :class => "mdl-button"  %>
            <%= link_to 'Sign Up', new_user_path, :class => "mdl-button" %>
            <% end %>
          </div>
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row"></div>
        <div class="mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark">
          <a href="/" class="mdl-layout__tab">Home</a>
          <a href="/restaurants" class="mdl-layout__tab">Restaurants</a>
          <a href="/reviews" class="mdl-layout__tab">Reviews</a>
        </div>
      </header>
      <main class="mdl-layout__content">
        <%= yield %>
      </main>
      <footer class="mdl-mega-footer" id="main-footer">
        <div class="mdl-mega-footer__middle-section">
          <div class="mdl-mega-footer__drop-down-section">
            <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
            <h1 class="mdl-mega-footer__heading">Features</h1>
            <ul class="mdl-mega-footer__link-list">
              <li><a href="#">About</a></li>
              <li><a href="#">Terms</a></li>
              <li><a href="#">Partners</a></li>
              <li><a href="#">Updates</a></li>
            </ul>
          </div>

          <div class="mdl-mega-footer__drop-down-section">
            <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
            <h1 class="mdl-mega-footer__heading">Details</h1>
            <ul class="mdl-mega-footer__link-list">
              <li><a href="#">Specs</a></li>
              <li><a href="#">Tools</a></li>
              <li><a href="#">Resources</a></li>
            </ul>
          </div>

          <div class="mdl-mega-footer__drop-down-section">
            <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
            <h1 class="mdl-mega-footer__heading">Technology</h1>
            <ul class="mdl-mega-footer__link-list">
              <li><a href="#">How it works</a></li>
              <li><a href="#">Patterns</a></li>
              <li><a href="#">Usage</a></li>
              <li><a href="#">Products</a></li>
              <li><a href="#">Contracts</a></li>
            </ul>
          </div>

          <div class="mdl-mega-footer__drop-down-section">
            <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
            <h1 class="mdl-mega-footer__heading">FAQ</h1>
            <ul class="mdl-mega-footer__link-list">
              <li><a href="#">Questions</a></li>
              <li><a href="#">Answers</a></li>
              <li><a href="#">Contact us</a></li>
            </ul>
          </div>

        </div>

        <div class="mdl-mega-footer__bottom-section">
          <div class="mdl-logo">Title</div>
          <ul class="mdl-mega-footer__link-list">
            <li><a href="#">Help</a></li>
            <li><a href="#">Privacy & Terms</a></li>
          </ul>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<!-- @TODO: replace br's with divs -->
<%= form_for(@restaurant) do |f| %>
  <%= f.hidden_field :name %>
  <br>
  <br>
  <%= f.label :price %>
  <br>
  <%= f.radio_button :price, "Cheap" %> Cheap <br />
  <%= f.radio_button :price, "Medium" %> Medium <br />
  <%= f.radio_button :price, "Expensive" %> Expensive <br />
  <br>
  <%= f.label :cuisine %>
  <br>
  <%= f.radio_button :cuisine, "American" %> American
  <br>
  <%= f.radio_button :cuisine, "Italian" %> Italian
  <br>
  <%= f.radio_button :cuisine, "Chinese" %> Chinese
  <br>
  <%= f.radio_button :cuisine, "Japanese" %> Japanese
  <br>
  <%= f.radio_button :cuisine, "Mexican" %> Mexican
  <br>
  <%= f.radio_button :cuisine, "Indian" %> Indian
  <br>
  <%= f.radio_button :cuisine, "Cafe" %> Cafe
  <br>
  <%= f.radio_button :cuisine, "Mediterranean" %> Mediterranean
  <br>
  <%= f.radio_button :cuisine, "Middle Eastern" %> Middle Eastern
  <br>
  <%= f.radio_button :cuisine, "Vietnamese" %> Vietnamese
  <br>
  <%= f.radio_button :cuisine, "Korean BBQ" %> Korean BBQ
  <br>
  <%= f.radio_button :cuisine, "Thai" %> Thai
  <br>
  <%= f.radio_button :cuisine, "Pub" %> Pub
  <br>
  <%= f.radio_button :cuisine, "Portugese" %> Portugese
  <br>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <br>
  <%= f.label :photo, 'Photo URL' %>
  <%= f.text_field :photo %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Edit <%= @restaurant.name %></h2>
<%= render 'form' %>
<%= link_to 'Show', @restaurant %>
<%= link_to 'Back', restaurant_path %>

app/views/restaurants/home.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text">
      <h4>The Ultimate Decision</h4>
      Can't decide where to go out to eat? This website is for you! Click the button below to make the ultimate decision
    </div>
    <div class="mdl-card__actions">
      <div class="mdl-button mdl-js-button mdl-button--raised">
      <%= button_to "Pick Restaurant", :action => "random_restaurant", :class => "mdl-button mdl-js-button mdl-button--raised" %>
    </div>
  </div>
</section>

app/views/restaurants/index.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h4 class="mdl-cell mdl-cell--12-col">Restaurants</h4>
      <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
      <% @restaurants.each do |restaurant| %>
        <ul class="demo-list-icon mdl-list">
          <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
              <i class="material-icons mdl-list__item-icon">restaurant</i>
            <a href="restaurants/<%= restaurant.id %>"><%= restaurant.name %></a>
            </span>
          </li>
        </ul>
      <% end %>
    <div class="mdl-card__actions">
      <a href="restaurants/new" class="mdl-button">Add Restaurant</a>
    </div>
  </div>
</section>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>
<%= render partial: 'form' %>

app/views/restaurants/show.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-color--black-100 mdl-color-text--white" style="overflow:hidden">
  <img src="<%= @restaurant.photo %>" alt="<%= @restaurant.name %>">
  </header>
  <div class="mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
    <div class="mdl-card__supporting-text">
      <h4><%= @restaurant.name %></h4>
      <p>
        <strong>Price Range - </strong>
        <%= @restaurant.price %>
      </p>

      <p>
        <strong>Cuisine - </strong>
        <%= @restaurant.cuisine %>
      </p>

      <p>
        <strong>Location - </strong>
        <%= @restaurant.location %>
      </p>
    </div>

    <div class="mdl-card__actions">
      <%= link_to 'Add Review', new_review_path(:restaurant_id => @restaurant.id), :class => 'mdl-button' %>
      <% if @current_user.present? && @current_user.admin? %>
      <%= link_to 'Delete', restaurant_path(@restaurant.id), method: 'delete', :class => 'mdl-button' %>
      <%= link_to 'Edit', edit_restaurant_path(@restaurant.id), :class => 'mdl-button' %>
      <% end %>

    </div>
  </div>
</section>

app/views/reviews/_form.html.erb
<!-- @TODO: replace br's with divs -->
<%= form_for @review do |f| %>
<br>
<%= f.label :restaurant %>
<%= f.text_field :restaurant, :value => @restaurant.name %>
<br>
<br>
<%= f.label :rating %>
<br>
<%= f.radio_button :rating, "1" %> 1 <br />
<%= f.radio_button :rating, "2" %> 2 <br />
<%= f.radio_button :rating, "3" %> 3 <br />
<%= f.radio_button :rating, "4" %> 4 <br />
<%= f.radio_button :rating, "5" %> 5 <br />
<br>

<%= f.label :comment %>
<%= f.text_field :comment %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h4 class="mdl-cell mdl-cell--12-col">Reviews</h4>
      <% @reviews.each do |review| %>
      <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone"></div>
      <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        <h5><%= review.restaurant %></h5><br>
        <p>Rating: <%= review.rating %></p><br>
        <p>Comment: <%= review.comment %></p><br>
        <% if @current_user.present? && @current_user.admin? %>
        <%= link_to 'Delete', method: 'delete', :class => 'mdl-button' %>
        <% end %>
      </div>
      <% end %>
  </div>
</section>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<%= render 'reviewsform' %>

app/views/session/new.html.erb
<h2>Login</h2>
<% if flash[:error] %>
  <br>
  <strong><%= flash[:error] %></strong>
  <br>
  <br>
<% end %>
<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag 'Login' %>
<% end %>

app/views/users/edit.html.erb
<h1>Users #edit</h1>

app/views/users/index.html.erb
<h2>All Users</h2>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Create New Account</h2>

<% if @user.errors.any? %>
<p>Please correct the following errors:</p>
<ul>
  <% @user.errors.full_messages.each do |e| %>
  <li><%= e %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h2>Welcome, <%= @user.name %></h2>